### PR TITLE
Title for Tag pages and sitemap.xml

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @danurbanowicz 

to save you some work I've added the titles to the tag pages as you described. I've also added a sitemap.xml in. Let me know if you don't want it and I'll remove it.

Cheers,
Peter

### CODE REVIEW

**Comment by danurbanowicz** [comment]
Thanks for this @spekulatius

I would prefer not to include the sitemap in the project as it makes some assumptions which I don't feel should be made by us e.g. which pages to include in the sitemap. I don't feel comfortable with users having a sitemap that they didn't ask for sitting in their project root, and perhaps don't even know is there.

(also in the [deploy preview](https://deploy-preview-15--eleventy-netlify-boilerplate.netlify.com/sitemap.xml) the sitemap.njk is not outputting all of the tag pages into the xml file, not sure why)

**Comment by spekulatius** [comment]
Hello @danurbanowicz 

I totally understand if you aren't keen on bringing in assumptions - I've removed the sitemap and updated the PR.

Not sure why not all tags where included - I've checked and found the same on my site. Thanks for point it out. I'll have a look 👍️

Peter

**Comment by danurbanowicz** [comment]
Thanks again for this @spekulatius !

**Comment by spekulatius** [comment]
No Problem!

**Pull request merged**
